# encoding: utf-8
source 'https://rubygems.org'

gem 'berkshelf'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'kitchen-rackspace'
gem 'kitchen-ssh'
gem 'chef-zero'
gem 'foodcritic'
gem 'rspec'
gem 'chefspec'
gem 'specinfra'
gem 'strainer'
gem 'busser'
gem 'busser-serverspec'
gem 'knife-rackspace'
gem 'serverspec'
gem 'rubocop'
gem 'vagrant-wrapper'
